apiVersion: dhcp.xfix.org/v1alpha1
kind: PXE
metadata:
  name: k-test-worker
spec:
  data: |
    #!ipxe

    kernel http://10.171.120.1:9999/static/talos-1.5.2-vmlinuz-amd64 slab_nomerge pti=on talos.platform=metal talos.config=http://10.171.120.1:8888/register?role=worker&token=welcome123
    initrd http://10.171.120.1:9999/static/talos-1.5.2-initramfs-amd64.xz
    boot
